const BMP_HEADER_LENGTH = 6;

const BMP_VERSION = {
    V3: 3,
    V4: 4
};

const BMP_V4_TLV_DRAFT = {
    DRAFT_19: 19,
    DRAFT_20: 20
};

const BMP_INITIATION_TLV_TYPE = {
    STRING: 0,
    SYS_DESC: 1,
    SYS_NAME: 2,
    VRF_TABLE_NAME: 3
};

// BMP peer types
const BMP_PEER_TYPE = {
    GLOBAL: 0,
    L3VPN: 1,
    LOCAL: 2,
    LOCAL_RIB: 3
};

const BMP_SESSION_FLAGS = {
    IPV6: 0x80, // V 位: 使用 IPv6 地址
    POST_POLICY: 0x40, // L 位: Post-policy；未设置表示 Pre-policy
    AS_PATH: 0x20, // A 位: legacy 2-byte AS_PATH 编码；不是 RIB stage
    ADJ_RIB_OUT: 0x10, // O 位: Adj-RIB-Out；未设置表示 Adj-RIB-In
    FILTERED: 0x08, // F 位: Local-RIB filtered
    EXTENDED_FLAGS: 0x01 // X 位: Extended Flags TLV carries effective flags
};

const BMP_LOC_RIB_FLAGS = {
    FILTERED: 0x80
};

const BMP_SESSION_STATE = {
    PEER_UP: 0,
    PEER_DOWN: 1
};

const BMP_ROUTE_UPDATE_TYPE = {
    ROUTE_DELETE: 0,
    ROUTE_UPDATE: 1,
    ROUTE_STALE: 2
};

const BMP_ROUTE_STATE = {
    ACTIVE: 'active',
    STALE: 'stale'
};

const BMP_ROUTE_STATE_FILTER = {
    ACTIVE: 'active',
    STALE: 'stale',
    ALL: 'all'
};

const BMP_ROUTE_PARSE_STATUS = {
    OK: 0,
    WARNING: 0x01,
    ERROR: 0x02
};

// BMP message types (RFC 7854)
const BMP_MSG_TYPE = {
    ROUTE_MONITORING: 0,
    STATISTICS_REPORT: 1,
    PEER_DOWN_NOTIFICATION: 2,
    PEER_UP_NOTIFICATION: 3,
    INITIATION: 4,
    TERMINATION: 5,
    ROUTE_MIRRORING: 6
};

const BMP_MSG_TYPE_NAME = {
    [BMP_MSG_TYPE.ROUTE_MONITORING]: 'ROUTE_MONITORING',
    [BMP_MSG_TYPE.STATISTICS_REPORT]: 'STATISTICS_REPORT',
    [BMP_MSG_TYPE.PEER_DOWN_NOTIFICATION]: 'PEER_DOWN_NOTIFICATION',
    [BMP_MSG_TYPE.PEER_UP_NOTIFICATION]: 'PEER_UP_NOTIFICATION',
    [BMP_MSG_TYPE.INITIATION]: 'INITIATION',
    [BMP_MSG_TYPE.TERMINATION]: 'TERMINATION',
    [BMP_MSG_TYPE.ROUTE_MIRRORING]: 'ROUTE_MIRRORING'
};

const BMP_TLV_TYPE = {
    SEQUENCE_NUMBER: 1,
    EXTENDED_FLAGS: 2,
    TIMESTAMP: 3
};

const BMP_ROUTE_MONITORING_TLV_TYPE = {
    ...BMP_TLV_TYPE,
    GROUP: 4,
    VRF_TABLE_NAME: 5,
    STATELESS_PARSING: 6,
    BGP_MESSAGE: 7,
    PATH_MARKING: 8
};

const BMP_ROUTE_MONITORING_TLV_TYPE_LEGACY = {
    STATELESS_PARSING: 1,
    GROUP: 2,
    VRF_TABLE_NAME: 3,
    BGP_MESSAGE: 4,
    PATH_MARKING: 5
};

const BMP_PATH_STATUS = {
    INVALID: 0x00000001,
    BEST: 0x00000002,
    NONSELECTED: 0x00000004,
    PRIMARY: 0x00000008,
    BACKUP: 0x00000010,
    NON_INSTALLED: 0x00000020,
    BEST_EXTERNAL: 0x00000040,
    ADD_PATH: 0x00000080,
    FILTERED_IN_INBOUND_POLICY: 0x00000100,
    FILTERED_IN_OUTBOUND_POLICY: 0x00000200,
    STALE: 0x00000400,
    SUPPRESSED: 0x00000800
};

const BMP_PATH_STATUS_NAME = {
    [BMP_PATH_STATUS.INVALID]: 'Invalid',
    [BMP_PATH_STATUS.BEST]: 'Best',
    [BMP_PATH_STATUS.NONSELECTED]: 'Nonselected',
    [BMP_PATH_STATUS.PRIMARY]: 'Primary',
    [BMP_PATH_STATUS.BACKUP]: 'Backup',
    [BMP_PATH_STATUS.NON_INSTALLED]: 'Non-installed',
    [BMP_PATH_STATUS.BEST_EXTERNAL]: 'Best-external',
    [BMP_PATH_STATUS.ADD_PATH]: 'Add-Path',
    [BMP_PATH_STATUS.FILTERED_IN_INBOUND_POLICY]: 'Filtered in inbound policy',
    [BMP_PATH_STATUS.FILTERED_IN_OUTBOUND_POLICY]: 'Filtered in outbound policy',
    [BMP_PATH_STATUS.STALE]: 'Stale',
    [BMP_PATH_STATUS.SUPPRESSED]: 'Suppressed'
};

const BMP_PATH_STATUS_REASON = {
    INVALID_AS_LOOP: 0x0001,
    INVALID_UNRESOLVABLE_NEXTHOP: 0x0002,
    NOT_PREFERRED_LOCAL_PREFERENCE: 0x0003,
    NOT_PREFERRED_AS_PATH_LENGTH: 0x0004,
    NOT_PREFERRED_ORIGIN: 0x0005,
    NOT_PREFERRED_MED: 0x0006,
    NOT_PREFERRED_PEER_TYPE: 0x0007,
    NOT_PREFERRED_IGP_COST: 0x0008,
    NOT_PREFERRED_ROUTER_ID: 0x0009,
    NOT_PREFERRED_PEER_ADDRESS: 0x000a,
    NOT_PREFERRED_AIGP: 0x000b
};

const BMP_PATH_STATUS_REASON_NAME = {
    [BMP_PATH_STATUS_REASON.INVALID_AS_LOOP]: 'Invalid due to AS loop',
    [BMP_PATH_STATUS_REASON.INVALID_UNRESOLVABLE_NEXTHOP]: 'Invalid due to unresolvable nexthop',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_LOCAL_PREFERENCE]: 'Not preferred for local preference',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_AS_PATH_LENGTH]: 'Not preferred for AS Path Length',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_ORIGIN]: 'Not preferred for origin',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_MED]: 'Not preferred for MED',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_PEER_TYPE]: 'Not preferred for peer type',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_IGP_COST]: 'Not preferred for IGP cost',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_ROUTER_ID]: 'Not preferred for router ID',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_PEER_ADDRESS]: 'Not preferred for peer address',
    [BMP_PATH_STATUS_REASON.NOT_PREFERRED_AIGP]: 'Not preferred for AIGP'
};

const BMP_STATS_REPORT_TLV_TYPE = {
    STATS: 1,
    ...BMP_TLV_TYPE
};

const BMP_PEER_DOWN_REASON = {
    LOCAL_SYSTEM_CLOSED_WITH_NOTIFICATION: 1,
    LOCAL_SYSTEM_CLOSED_NO_NOTIFICATION: 2,
    REMOTE_SYSTEM_CLOSED_WITH_NOTIFICATION: 3,
    REMOTE_SYSTEM_CLOSED_NO_NOTIFICATION: 4,
    PEER_DE_CONFIGURED: 5,
    LOCAL_SYSTEM_CLOSED_WITH_TLV: 6
};

// 事件类型
const BMP_EVT_TYPES = {
    INITIATION: 1,
    SESSION_UPDATE: 2,
    ROUTE_UPDATE: 3,
    TERMINATION: 4,
    INSTANCE_UPDATE: 5,
    INSTANCE_ROUTE_UPDATE: 6,
    STATISTICS_REPORT: 7
};

// BMP请求-响应类型
const BMP_REQ_TYPES = {
    START_BMP: 1,
    STOP_BMP: 2,
    GET_CLIENT_LIST: 3,
    GET_BGP_SESSIONS: 4,
    GET_BGP_ROUTES: 5,
    GET_BGP_INSTANCES: 6,
    GET_BGP_INSTANCE_ROUTES: 7,
    PURGE_STALE_BGP_ROUTES: 8,
    PURGE_STALE_BGP_INSTANCE_ROUTES: 9,
    GET_BGP_STATISTICS_REPORTS: 10,
    GET_BGP_INSTANCE_STATISTICS_REPORTS: 11,
    GET_BGP_ROUTE_DETAIL: 12,
    GET_BGP_INSTANCE_ROUTE_DETAIL: 13,
    GET_ROUTE_LENS: 14,
    GET_ROUTE_ASSURANCE: 15,
    SET_ROUTE_ASSURANCE_ENABLED: 16,
    GET_PERSISTENCE_STATUS: 17,
    GET_PERSISTED_ROUTES: 18,
    GET_PERSISTED_ROUTE_EVENTS: 19,
    DELETE_CLIENT_DATA: 20,
    GET_CLIENT: 21
};

const BMP_BGP_RIB_TYPE = {
    PRE_ADJ_RIB_IN: 1,
    ADJ_RIB_IN: 2,
    AS_PATH: 3, // Legacy compatibility only; BMP A is an AS_PATH encoding flag, not a RIB stage.
    ADJ_RIB_OUT: 4,
    POST_ADJ_RIB_OUT: 5
};

// BMP Statistics Types (RFC 7854, RFC 8671, and RFC 9972)
const BMP_STATS_TYPE = {
    NUM_PREFIXES_REJECTED: 0,
    NUM_DUPLICATE_PREFIX_ADVERTISEMENTS: 1,
    NUM_DUPLICATE_WITHDRAWS: 2,
    NUM_UPDATES_INVALIDATED_CLUSTER_LIST: 3,
    NUM_UPDATES_INVALIDATED_AS_PATH_LOOP: 4,
    NUM_UPDATES_INVALIDATED_ORIGINATOR_ID: 5,
    NUM_UPDATES_INVALIDATED_AS_CONFED_LOOP: 6,
    NUM_ADJ_RIB_IN: 7,
    NUM_LOC_RIB: 8,
    NUM_PER_AFI_SAFI_ADJ_RIB_IN: 9,
    NUM_PER_AFI_SAFI_LOC_RIB: 10,
    NUM_UPDATES_TREATED_AS_WITHDRAW: 11,
    NUM_PREFIXES_TREATED_AS_WITHDRAW: 12,
    NUM_DUPLICATE_UPDATE_MESSAGES: 13,
    NUM_PRE_POLICY_ADJ_RIB_OUT: 14,
    NUM_POST_POLICY_ADJ_RIB_OUT: 15,
    NUM_PER_AFI_SAFI_PRE_POLICY_ADJ_RIB_OUT: 16,
    NUM_PER_AFI_SAFI_POST_POLICY_ADJ_RIB_OUT: 17,
    NUM_PRE_POLICY_ADJ_RIB_IN: 18,
    NUM_PER_AFI_SAFI_PRE_POLICY_ADJ_RIB_IN: 19,
    NUM_POST_POLICY_ADJ_RIB_IN: 20,
    NUM_PER_AFI_SAFI_POST_POLICY_ADJ_RIB_IN: 21
};

const BMP_STATS_TYPE_NAME = {
    [BMP_STATS_TYPE.NUM_PREFIXES_REJECTED]: '拒绝的前缀数',
    [BMP_STATS_TYPE.NUM_DUPLICATE_PREFIX_ADVERTISEMENTS]: '重复的前缀通告数',
    [BMP_STATS_TYPE.NUM_DUPLICATE_WITHDRAWS]: '重复的撤销数',
    [BMP_STATS_TYPE.NUM_UPDATES_INVALIDATED_CLUSTER_LIST]: '因 Cluster List 无效的更新数',
    [BMP_STATS_TYPE.NUM_UPDATES_INVALIDATED_AS_PATH_LOOP]: '因 AS Path 环路无效的更新数',
    [BMP_STATS_TYPE.NUM_UPDATES_INVALIDATED_ORIGINATOR_ID]: '因 Originator ID 无效的更新数',
    [BMP_STATS_TYPE.NUM_UPDATES_INVALIDATED_AS_CONFED_LOOP]: '因 AS Confed 环路无效的更新数',
    [BMP_STATS_TYPE.NUM_ADJ_RIB_IN]: 'Adj-RIB-In 中的路由数',
    [BMP_STATS_TYPE.NUM_LOC_RIB]: 'Loc-RIB 中的路由数',
    [BMP_STATS_TYPE.NUM_PER_AFI_SAFI_ADJ_RIB_IN]: '每 AFI/SAFI Adj-RIB-In 中的路由数',
    [BMP_STATS_TYPE.NUM_PER_AFI_SAFI_LOC_RIB]: '每 AFI/SAFI Loc-RIB 中的路由数',
    [BMP_STATS_TYPE.NUM_UPDATES_TREATED_AS_WITHDRAW]: '被视为撤销的更新数',
    [BMP_STATS_TYPE.NUM_PREFIXES_TREATED_AS_WITHDRAW]: '被视为撤销的前缀数',
    [BMP_STATS_TYPE.NUM_DUPLICATE_UPDATE_MESSAGES]: '重复的更新消息数',
    [BMP_STATS_TYPE.NUM_PRE_POLICY_ADJ_RIB_OUT]: 'Pre-Policy Adj-RIB-Out 中的路由数',
    [BMP_STATS_TYPE.NUM_POST_POLICY_ADJ_RIB_OUT]: 'Post-Policy Adj-RIB-Out 中的路由数',
    [BMP_STATS_TYPE.NUM_PER_AFI_SAFI_PRE_POLICY_ADJ_RIB_OUT]: '每 AFI/SAFI Pre-Policy Adj-RIB-Out 中的路由数',
    [BMP_STATS_TYPE.NUM_PER_AFI_SAFI_POST_POLICY_ADJ_RIB_OUT]: '每 AFI/SAFI Post-Policy Adj-RIB-Out 中的路由数',
    [BMP_STATS_TYPE.NUM_PRE_POLICY_ADJ_RIB_IN]: 'Pre-Policy Adj-RIB-In 中的路由数',
    [BMP_STATS_TYPE.NUM_PER_AFI_SAFI_PRE_POLICY_ADJ_RIB_IN]: '每 AFI/SAFI Pre-Policy Adj-RIB-In 中的路由数',
    [BMP_STATS_TYPE.NUM_POST_POLICY_ADJ_RIB_IN]: 'Post-Policy Adj-RIB-In 中的路由数',
    [BMP_STATS_TYPE.NUM_PER_AFI_SAFI_POST_POLICY_ADJ_RIB_IN]: '每 AFI/SAFI Post-Policy Adj-RIB-In 中的路由数'
};

const BMP_LOC_RIB_STATS_TYPE_NAME = {
    [BMP_STATS_TYPE.NUM_LOC_RIB]: 'Loc-RIB 中的路由数',
    [BMP_STATS_TYPE.NUM_PER_AFI_SAFI_LOC_RIB]: '每 AFI/SAFI Loc-RIB 中的路由数'
};

module.exports = {
    BMP_HEADER_LENGTH,
    BMP_VERSION,
    BMP_V4_TLV_DRAFT,
    BMP_MSG_TYPE,
    BMP_PEER_TYPE,
    BMP_SESSION_FLAGS,
    BMP_LOC_RIB_FLAGS,
    BMP_MSG_TYPE_NAME,
    BMP_INITIATION_TLV_TYPE,
    BMP_TLV_TYPE,
    BMP_ROUTE_MONITORING_TLV_TYPE,
    BMP_ROUTE_MONITORING_TLV_TYPE_LEGACY,
    BMP_PATH_STATUS,
    BMP_PATH_STATUS_NAME,
    BMP_PATH_STATUS_REASON,
    BMP_PATH_STATUS_REASON_NAME,
    BMP_STATS_REPORT_TLV_TYPE,
    BMP_PEER_DOWN_REASON,
    BMP_SESSION_STATE,
    BMP_ROUTE_UPDATE_TYPE,
    BMP_ROUTE_STATE,
    BMP_ROUTE_STATE_FILTER,
    BMP_ROUTE_PARSE_STATUS,
    BMP_EVT_TYPES,
    BMP_REQ_TYPES,
    BMP_BGP_RIB_TYPE,
    BMP_STATS_TYPE,
    BMP_STATS_TYPE_NAME,
    BMP_LOC_RIB_STATS_TYPE_NAME
};
