const RPKI_HEADER_LENGTH = 8;

// RPKI message types (RFC 6810 / RFC 8210 / draft-ietf-sidrops-8210bis)
const RPKI_MSG_TYPE = {
    SERIAL_NOTIFY: 0,
    SERIAL_QUERY: 1,
    RESET_QUERY: 2,
    CACHE_RESPONSE: 3,
    IPV4_PREFIX: 4,
    IPV6_PREFIX: 6,
    END_OF_DATA: 7,
    CACHE_RESET: 8,
    ROUTER_KEY: 9, // v1+
    ERROR_REPORT: 10,
    ASPA: 11 // v2+
};

const RPKI_MSG_TYPE_NAME = {
    [RPKI_MSG_TYPE.SERIAL_NOTIFY]: 'SERIAL_NOTIFY',
    [RPKI_MSG_TYPE.SERIAL_QUERY]: 'SERIAL_QUERY',
    [RPKI_MSG_TYPE.RESET_QUERY]: 'RESET_QUERY',
    [RPKI_MSG_TYPE.CACHE_RESPONSE]: 'CACHE_RESPONSE',
    [RPKI_MSG_TYPE.IPV4_PREFIX]: 'IPV4_PREFIX',
    [RPKI_MSG_TYPE.IPV6_PREFIX]: 'IPV6_PREFIX',
    [RPKI_MSG_TYPE.END_OF_DATA]: 'END_OF_DATA',
    [RPKI_MSG_TYPE.CACHE_RESET]: 'CACHE_RESET',
    [RPKI_MSG_TYPE.ROUTER_KEY]: 'ROUTER_KEY',
    [RPKI_MSG_TYPE.ERROR_REPORT]: 'ERROR_REPORT',
    [RPKI_MSG_TYPE.ASPA]: 'ASPA'
};

// RPKI Protocol Version
const RPKI_PROTOCOL_VERSION = {
    V0: 0,
    V1: 1,
    V2: 2
};

// 服务端支持的最高协议版本
const RPKI_MAX_SUPPORTED_VERSION = RPKI_PROTOCOL_VERSION.V2;

// RPKI Error Codes
const RPKI_ERROR_CODE = {
    CORRUPT_DATA: 0,
    INTERNAL_ERROR: 1,
    NO_DATA_AVAILABLE: 2,
    INVALID_REQUEST: 3,
    UNSUPPORTED_PROTOCOL_VERSION: 4,
    UNSUPPORTED_PDU_TYPE: 5,
    WITHDRAWAL_UNKNOWN: 6,
    DUPLICATE_ANNOUNCEMENT: 7,
    UNEXPECTED_PROTOCOL_VERSION: 8
};

// RPKI PDU Flags
const RPKI_FLAGS = {
    WITHDRAWAL: 0x00,
    UPDATE: 0x01
};

// ASPA AFI Flags (v2)
const RPKI_ASPA_AFI_FLAGS = {
    IPV4: 0x01,
    IPV6: 0x02
};

// ASPA PDU 编码格式
// LATEST = current draft-ietf-sidrops-8210bis format (byte3=zero, 无 Provider Count)
// LEGACY = draft-ietf-sidrops-8210bis-10 风格 (body 含 Flags/AFI Flags/Provider AS Count，华为 VRP 兼容)
const RPKI_ASPA_FORMAT = {
    LATEST: 'latest',
    LEGACY: 'legacy'
};

// RPKI ROA Status
const RPKI_ROA_STATUS = {
    ACTIVE: 'active',
    PENDING: 'pending'
};

// Default RPKI Port
const RPKI_DEFAULT_PORT = 8282;

// 事件类型
const RPKI_EVT_TYPES = {
    CLIENT_CONNECTION: 1
};

// RPKI请求-响应类型
const RPKI_REQ_TYPES = {
    START_RPKI: 1,
    STOP_RPKI: 2,
    ADD_ROA: 3,
    DELETE_ROA: 4,
    GET_CLIENT_LIST: 5,
    ADD_ROUTER_KEY: 6,
    DELETE_ROUTER_KEY: 7,
    ADD_ASPA: 8,
    DELETE_ASPA: 9
};

module.exports = {
    RPKI_HEADER_LENGTH,
    RPKI_MSG_TYPE,
    RPKI_MSG_TYPE_NAME,
    RPKI_PROTOCOL_VERSION,
    RPKI_MAX_SUPPORTED_VERSION,
    RPKI_ERROR_CODE,
    RPKI_FLAGS,
    RPKI_ASPA_AFI_FLAGS,
    RPKI_ASPA_FORMAT,
    RPKI_ROA_STATUS,
    RPKI_DEFAULT_PORT,
    RPKI_EVT_TYPES,
    RPKI_REQ_TYPES
};
